import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionProvider from "@/components/SessionProvider";
import { ThemeProvider } from "@/components/ThemeProvider";
import Navbar from "@/components/navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const themeOptions = {
    // attribute: "class",
    defaultTheme: "blue",
    enableSystem: true,
  };
  return (
    <html lang="en" suppressHydrationWarning >
      <head>
        {process.env.NODE_ENV == "production" && <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2233066744078073"
          crossOrigin="anonymous"></script>}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative w-full h-full `}
      >

        <SessionProvider >
          <ThemeProvider {...themeOptions} attribute={"class"}>
            <Navbar />
            <div className="w-72 h-72 rounded-full bg-purple-600/30 blur-[128px] absolute  left-5 top-0 z-[-1]" />
            <div className="w-72 h-72 rounded-full bg-purple-600/20 blur-[128px] absolute  left-20 top-[50%] z-[-1]" />
            <div className="w-72 h-72 rounded-full bg-purple-600/30 blur-[128px] absolute  right-0 top-[70%] z-[-1]" />
            {children}

          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
